-   id: powershell-check
    name: powershell-check
    entry: powershell Invoke-ScriptAnalyzer -path 
    language: system
    files: '\.(ps1)$'
-   id: dotnet-format
    name: dotnet-format
    entry: dotnet format --files
    language: system
    files: '\.(cs|vb)$'
-   id: dotnet-test
    name: dotnet Unit test
    entry: dotnet-test.sh
    language: script
    files: '\.(cs|vb)$'
